import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { AppThemeProvider, Navbar } from "@/components/ui";
import "./globals.css";

const poppins = Poppins({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wander Trails",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={poppins.className}>
          <AppThemeProvider>
            <Navbar />
            <main className="root-container">{children}</main>
          </AppThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
